apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mypod
  name: mypod
spec:
  securityContext:
    runAsUser: 5000
    runAsGroup: 5000
    fsGroup: 5000
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /home/vagrant/mountme
      # this field is optional
      type: Directory
  serviceAccountName: pod-creator
  #nodeName: kubemaster  ## not necessary
  containers:
  - image: localhost:5000/mypod:v10
    name: mypod
    volumeMounts:
    - mountPath: /myfolder
      name: test-volume
  restartPolicy: Never
