apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        runAsUser: 5000
        runAsGroup: 5000
        fsGroup: 5000
      volumes:
      - name: test-volume
        hostPath:
          # directory location on host
          path: /home/vagrant/mountme
          # this field is optional
          type: Directory
      serviceAccountName: pod-creator
      containers:
      - name: nginx
        image: nginx:1.15.4
        volumeMounts:
        - mountPath: /myfolder
          name: test-volume
        ports:
        - containerPort: 80
